# .goreleaser.yml
project_name: netfetch

# Changelog Configuration
changelog:
  sort: desc
  filters:
    exclude:
      - '^Merge pull request'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Documentation Updates"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other Changes"
      regexp: "^(ci|build|misc|perf|deps):"
      order: 3
    - title: "Miscellaneous"
      regexp: ".*"
      order: 4

# Build Configuration
builds:
  - id: "netfetch"
    main: ./backend/main.go
    binary: netfetch
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X 'github.com/deggja/netfetch/backend/cmd.Version={{.Version}}'
    # Additional build flags can be added here

# Archive Configuration
archives:
  - id: "archive"
    builds:
      - netfetch
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

# Release Configuration
release:
  github:
    owner: deggja
    name: netfetch
  draft: false
