# Default values for netfetch.
replicaCount: 1

image:
  repository: deggja/netfetch
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  # allowPrivilegeEscalation: false
  # privileged: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: "nginx"
  annotations:
   # cert-manager.io/cluster-issuer: "letsencrypt-prod"
   # kubernetes.io/tls-acme: "true"
   # nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: netfetch.example.com  # Update this to reflect your domain
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - netfetch.example.com
      secretName: netfetch-tls

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  create: true
  clusterWideAccess: true